kafka:
  brokers:
    - kafka-0:9092

# Ajout de la section Kafka Connect
kafkaConnect:
  enabled: true
  clusters:
    - name: "cluster-connect"
      url: "http://kafka-connect:8083"
      
server:
  listenPort: 8080
